### ISSUE TITLE
now working on new mac os 

### ISSUE THREAD

**Issue by dominiksipowicz** [inolen/quakejs#23]
Hi quakejs dosn't work on MacOS 10.12.3 and chrome.

**Comment by LWSS** [comment]
Is mouse-look not working or does the game not launch?

**Comment by timCF** [comment]
```
TypeError: panner.setVelocity is not a function
```

**Comment by LWSS** [comment]
Yeah i'm getting that too on Chrome, Firefox seems to work ok

**Comment by LWSS** [comment]
Looks to be deprecated
https://www.chromestatus.com/feature/5238926818148352

**Comment by inolen** [comment]
This should be fixed now :+1:

**Comment by LWSS** [comment]
If anyone else was wondering what he did to fix it, see here http://www.quakejs.com/js/38cbed8aa9a0bda4736d1aede69b4867-ioquake3.js

Instances of setVelocity were all commented out.
